In [9]:
import numpy as np
import scipy.linalg as la

In [3]:
def hadamard_product(matrix_A, matrix_B):
    '''
    Compute the Hadamard product of two matrices.

    Args:
    — matrix_A (numpy.ndarray): First matrix.
    — matrix_B (numpy.ndarray): Second matrix.

    Returns:
    — numpy.ndarray: Hadamard product of the input matrices.
    '''

    # Ensure matrices have the same shape
    if matrix_A.shape != matrix_B.shape:
        raise ValueError("Both matrices must have the same shape for Hadamard product.")

    return np.multiply(matrix_A, matrix_B)

In [6]:
A = np.array([[9,6,7,9,13]])
B = np.array([[8,7,17,4,13]])

c = hadamard_product(A,B)

c.sum()

438

In [12]:
A = np.array([
    [1.0, 0.8, 0.8, 0.7],
    [0.8, 1.0, 0.7, 0.8],
    [0.8, 0.7, 1.0, 0.8],
    [0.7, 0.8, 0.8, 1.0]
    ])
autovalores, autovetores = la.eig(A)

print(autovalores)
print(autovetores)

[3.3+0.j 0.3+0.j 0.1+0.j 0.3+0.j]
[[-5.00000000e-01 -7.07106781e-01  5.00000000e-01  8.06094260e-02]
 [-5.00000000e-01 -3.19954812e-16 -5.00000000e-01 -7.02497061e-01]
 [-5.00000000e-01 -5.62768436e-17 -5.00000000e-01  7.02497061e-01]
 [-5.00000000e-01  7.07106781e-01  5.00000000e-01 -8.06094260e-02]]


In [19]:
A = np.array([
    [10, 10, 10, 9, 7],
    [8, 9, 11, 5, 11],
    [11, 16, 8, 10, 9],
    [5, 7, 4, 6, 14],
    [10, 6, 9, 10, 10]
])

B = np.array([
    [3, 7, 8, 8, 11],
    [9, 9, 14, 11, 15],
    [10, 13, 9, 6, 6],
    [9, 6, 11, 7, 12],
    [12, 5, 11, 9, 11]
]) 

C = A + B

# C.sum()
C

array([[13, 17, 18, 17, 18],
       [17, 18, 25, 16, 26],
       [21, 29, 17, 16, 15],
       [14, 13, 15, 13, 26],
       [22, 11, 20, 19, 21]])

In [21]:
# Q6

A = np.array([
    [12, 16, 7, 7, 6],
    [7, 12, 15, 5, 9],
    [8, 8, 7, 12, 5],
    [13, 10, 12, 10, 5],
    [14, 7, 11, 11, 9]
])

alpha = 3

C = alpha*A

C.sum()

714

In [24]:
# Q7
A = np.array([
    [16, 15, 8, 11, 9],
    [8, 11, 10, 13, 11],
    [11, 9, 12, 5, 8],
    [18, 10, 10, 10, 12],
    [15, 14, 11, 7, 14]
])

B = np.array([
    [4, 11, 9, 9, 16],
    [14, 15, 15, 9, 13],
    [12, 9, 13, 11, 10],
    [10, 10, 10, 18, 11],
    [13, 7, 16, 13, 13]
])

C = A.dot(B)

C.sum()

16093

In [25]:
# Q8

A = np.array([[7, 7, 6, 9, 9]])
B = np.array([[8, 6, 19, 11, 9]])

c = hadamard_product(A,B)

c.sum()

392

In [119]:
#Q9
import scipy

V = np.array([
    [30.6, 0, 0, 0],
    [0, 1.8, 0, 0],
    [0, 0, 1.8, 0],
    [0, 0, 0, 1.8]
    ]
)

Q = np.array([
    [-0.5, -0.1108307,  0.76679383, -0.3869674],
    [-0.5, -0.1187031,  0.08747384,  0.8533803],
    [-0.5, -0.5734494, -0.56764881, -0.3145324],
    [-0.5,  0.8029832, -0.28661886, -0.1518805]
    ]
)

A = Q.dot(V).dot(Q.T)

A_inv = np.linalg.inv(A)

np.log(np.linalg.det(A_inv))

-5.184360122352768

In [83]:
# Q10

import scipy

# Defina sua matriz
A = np.array([[1.0, 0.8, 0.8, 0.8],
              [0.8, 1.0, 0.8, 0.8],
              [0.8, 0.8, 1.0, 0.8],
              [0.8, 0.8, 0.8, 1.0]])

b = np.array(
    [12, 8, 7, 9]
)

# Faça a decomposição LU
P, L, U = scipy.linalg.lu(A)

# LUX = b

y = np.linalg.solve(L, b)

y.sum()

9.203418803418801

In [ ]:
np.ex

In [106]:
A = np.array([
    [1.0, 0.8, 0.8, 0.7],
    [0.8, 1.0, 0.7, 0.8],
    [0.8, 0.7, 1.0, 0.8],
    [0.7, 0.8, 0.8, 1.0]
    ])

autovalores, autovetores = la.eig(A)

V = np.array([
    [autovalores[0], 0, 0, 0],
    [0, autovalores[1], 0, 0],
    [0, 0, autovalores[2], 0],
    [0, 0, 0, autovalores[3]]
])

Q = np.around(autovetores,6)

result = np.around(Q.dot(np.exp(V)).dot(Q.T), 2)

np.trace(result)

(30.69+0j)

In [108]:
# Q15

A = np.array([
    [12, 9, 10, 12, 14],
    [8, 11, 13, 12, 16],
    [9, 10, 13, 14, 8],
    [5, 15, 12, 10, 8],
    [9, 7, 10, 10, 11]
])

B = np.array([
    [15, 13, 11, 16, 5],
    [9, 12, 6, 13, 5],
    [11, 8, 8, 8, 8],
    [9, 8, 8, 6, 15],
    [5, 14, 10, 15, 10]
]) 

C = A - B

C.sum()


20

In [113]:
# Q20
A = np.array([
    [12, 8, 7, 5, 3]
])

B = np.array([
    [10, 9, 14, 15, 6]
])

C = A*B

C.sum()

383

In [115]:
# Q21

A = np.array([
    [17, 5, 10, 10, 12]
])

alpha = 12

b = alpha*A

b.sum()

648

In [117]:
# Q23
A = np.array([
    [13, 9, 13, 12, 10],
    [11, 7, 12, 9, 18],
    [14, 11, 8, 8, 8],
    [18, 9, 15, 17, 14],
    [5, 11, 9, 11, 4]
])

B = np.array([
    [10, 13, 17, 15, 11],
    [9, 11, 7, 6, 10],
    [13, 16, 8, 5, 11],
    [7, 9, 10, 9, 9],
    [14, 16, 12, 10, 8]
])

C = A+B

C.sum()



542